export const dummyNftData = [
  {
    id: 0,
    name: "Get Best Template Here",
    price: "0.3",
    likes: "30",
    views: "25",
    imgSrc: "assets/images/category/template/art_1.png",
    bidCount: "3/3",
    status: "",
    collection: "assets/images/user1.png",
    creator: "assets/images/user2.png",
    owner: "assets/images/user3.png"
  },
  {
    id: 1,
    name: "Are Looking For Amazing Template",
    price: "0.4",
    likes: "100",
    views: "70",
    imgSrc: "assets/images/category/template/art_2.png",
    bidCount: "76/76",
    status: "",
    collection: "assets/images/user1.png",
    creator: "assets/images/user2.png",
    owner: "assets/images/user3.png"
  },
  {
    id: 2,
    name: "Get Full Package Of Templates And Icon",
    price: "1.2",
    likes: "100",
    views: "43",
    imgSrc: "assets/images/category/template/art_3.png",
    bidCount: "31/31",
    status: "",
    collection: "assets/images/user1.png",
    creator: "assets/images/user2.png",
    owner: "assets/images/user3.png"
  },
  {
    id: 3,
    name: "Best B&W Template",
    price: "2.3",
    likes: "300",
    views: "205",
    imgSrc: "assets/images/category/template/art_4.png",
    bidCount: "33/33",
    status: "",
    collection: "assets/images/user1.png",
    creator: "assets/images/user2.png",
    owner: "assets/images/user3.png"
  },
  {
    id: 4,
    name: "Funny games for kid",
    price: "0.2",
    likes: "50",
    views: "22",
    imgSrc: "assets/images/category/game/art_3.gif",
    bidCount: "5/5",
    status: "",
    collection: "assets/images/user1.png",
    creator: "assets/images/user2.png",
    owner: "assets/images/user3.png"
  },
  {
    id: 5,
    name: "Easy to play car racing games",
    price: "0.7",
    likes: "60",
    views: "80",
    imgSrc: "assets/images/category/game/art_4.gif",
    bidCount: "70/70",
    status: "",
    collection: "assets/images/user1.png",
    creator: "assets/images/user2.png",
    owner: "assets/images/user3.png"
  },
  {
    id: 6,
    name: "Indoor Football Table Game",
    price: "0.6",
    likes: "310",
    views: "125",
    imgSrc: "assets/images/category/template/art_5.png",
    bidCount: "6/6",
    status: "",
    collection: "assets/images/user1.png",
    creator: "assets/images/user2.png",
    owner: "assets/images/user3.png"
  },
  {
    id: 7,
    name: "Get Mario Game",
    price: "0.8",
    likes: "130",
    views: "250",
    imgSrc: "assets/images/category/game/art_6.gif",
    bidCount: "22/22",
    status: "",
    collection: "assets/images/user1.png",
    creator: "assets/images/user2.png",
    owner: "assets/images/user3.png"
  },
  {
    id: 8,
    name: "Buy board game to play with family",
    price: "0.1",
    likes: "90",
    views: "32",
    imgSrc: "assets/images/category/game/art_7.gif",
    bidCount: "65/65",
    status: "",
    collection: "assets/images/user1.png",
    creator: "assets/images/user2.png",
    owner: "assets/images/user3.png"
  }
]
